services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    image: cs456-project-2:latest
    ports:
      - "8501:8501"
    environment:
      - STREAMLIT_SERVER_ENABLECORS=false
      - STREAMLIT_SERVER_PORT=8501
      - STREAMLIT_SERVER_ADDRESS=0.0.0.0
    volumes:
      - ./chroma_langchain_db:/app/chroma_langchain_db
      - ./app_data.sqlite:/app/app_data.sqlite
      - ./.streamlit:/app/.streamlit
    restart: unless-stopped
